vocalkiev/apps/crm/apps/schedule/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='crm-schedule'),
    path('<int:year>/', views.schedule_day),
    path('<int:year>/<int:month>/', views.schedule_day),
    path('<int:year>/<int:month>/<int:day>/', views.schedule_day, name='crm-schedule-day'),
    path('<int:year>/<int:month>/<int:day>/<int:place_id>/', views.schedule_day, name='crm-schedule-day-place'),
]

vocalkiev/urls.py
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from vocalkiev.settings import LOGIN_URL
from vocalkiev.apps.owner.admin import owner_admin_site
from django.contrib.auth.decorators import login_required, user_passes_test
from decorator_include import decorator_include
from django.contrib.auth.views import LoginView

urlpatterns = [
    path(LOGIN_URL, LoginView.as_view(template_name='admin/login.html'))
]

urlpatterns += i18n_patterns(
    path('', include('vocalkiev.apps.vocalkiev_com.urls')),
    path(
        'owner/',
        decorator_include(
            user_passes_test(lambda u: u.is_superuser, login_url=f'/{LOGIN_URL}'),
            owner_admin_site.urls
        )
    ),
    path('crm/', decorator_include(login_required(login_url=f'/{LOGIN_URL}'), include('vocalkiev.apps.crm.urls'))),
)

vocalkiev/apps/crm/models.py
from django.utils import timezone

from django.db import models
from django.contrib.auth.models import User as AuthUser
from django.utils.translation import gettext_lazy as _


class User(AuthUser):
    class Meta:
        proxy = True
        verbose_name = _('User')
        verbose_name_plural = _('Users')

    def __str__(self):
        return ('%s %s' % (self.first_name, self.last_name)).strip()


class Status(models.TextChoices):
    ACTIVE = 'ACTIVE', _('ACTIVE')
    INACTIVE = 'INACTIVE', _('INACTIVE')


class PaymentType(models.TextChoices):
    CASH = 'CASH', _('CASH')
    CARD = 'CARD', _('CARD')


class Model(models.Model):
    status = models.CharField(max_length=10, choices=Status.choices, default=Status.ACTIVE)
    creator = models.ForeignKey(
        User,
        models.CASCADE,
        related_name="%(app_label)s_%(class)s_related"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = models.Manager()

    class Meta:
        abstract = True


class Client(Model):
    first_name = models.CharField(blank=True, max_length=64)
    last_name = models.CharField(blank=True, max_length=64, default='')
    email = models.EmailField(blank=True)
    phone = models.CharField(blank=True, max_length=20)
    comment = models.TextField(blank=True)

    class Meta:
        verbose_name = _('Client')
        verbose_name_plural = _('Clients')

    def __str__(self):
        return ('%s %s' % (self.first_name, self.last_name)).strip()


class ClientComment(Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    comment = models.TextField(max_length=200, blank=True, default='')

    class Meta:
        verbose_name = _('Client Comment')
        verbose_name_plural = _('Client Comments')

    def __str__(self):
        dt = self.created_at.strftime('%d.%m.%Y %H:%M')
        return f"{dt} {self.creator}: {self.comment}"


class Place(Model):
    name = models.CharField(max_length=64)

    class Meta:
        verbose_name = _('Place')
        verbose_name_plural = _('Places')

    def __str__(self):
        return self.name


class Classroom(Model):
    place = models.ForeignKey(Place, models.CASCADE)
    name = models.CharField(max_length=64)

    class Meta:
        verbose_name = _('Classroom')
        verbose_name_plural = _('Classrooms')

    def __str__(self):
        return f"{self.place} {self.name}"


class Subject(Model):
    name = models.CharField(max_length=64)

    class Meta:
        verbose_name = _('Subject')
        verbose_name_plural = _('Subjects')

    def __str__(self):
        return self.name


class Subscription(Model):
    subject = models.ForeignKey(Subject, models.CASCADE)
    name = models.CharField(max_length=64)
    price = models.FloatField(default=0)
    percentage = models.FloatField(default=0)
    lessons_qty = models.IntegerField(default=0)
    percentage_if_absent = models.FloatField(default=0)

    class Meta:
        verbose_name = _('Subscription')
        verbose_name_plural = _('Subscriptions')

    def __str__(self):
        return f"{self.subject} {self.name} ({self.price}{_('uah')})"


class ClientSubscription(Model):
    subscription = models.ForeignKey(Subscription, models.CASCADE)
    client = models.ForeignKey(Client, models.CASCADE)
    teacher = models.ForeignKey(User, models.CASCADE, related_name='subscription_teacher')
    comment = models.TextField(max_length=500, blank=True)
    payment_type = models.CharField(max_length=10, choices=PaymentType.choices)

    class Meta:
        verbose_name = _('Client Subscription')
        verbose_name_plural = _('Client Subscriptions')

    def can_create_lesson(self):
        return self.subscription.lessons_qty > self.lesson_set.count()

    def get_passed_lessons_count(self):
        return self.lesson_set.filter(is_passed=True).count()

    def can_archive(self):
        return self.subscription.lessons_qty == self.get_passed_lessons_count()

    def __str__(self):
        return f"{self.client}, {self.teacher.last_name}, {self.subscription}"


class Lesson(Model):
    client_subscription = models.ForeignKey(ClientSubscription, models.CASCADE)
    teacher = models.ForeignKey(User, models.CASCADE, related_name='lesson_teacher')
    classroom = models.ForeignKey(Classroom, models.CASCADE)
    datetime = models.DateTimeField(_('Time of the event'))
    is_passed = models.BooleanField(_('Is passed'), default=False)
    was_absent = models.BooleanField(_('Was absent'), default=False)

    class Meta:
        verbose_name = _('Lesson')
        verbose_name_plural = _('Lessons')

    def teacher_amount(self):
        if not self.is_passed:
            return 0

        s = self.client_subscription.subscription
        lesson_price = s.price / s.lessons_qty
        percentage = s.percentage if not self.was_absent else s.percentage_if_absent
        return lesson_price * percentage / 100

    def can_pass(self):
        return not self.is_passed and timezone.now() > self.datetime

    def diff_in_hours_for_now(self):
        return (self.datetime - timezone.now()).total_seconds() / 60 / 60

    def can_update_by_teacher(self):
        return self.diff_in_hours_for_now() > 18  # Eighteen

    def can_update_by_administrator(self):
        return self.diff_in_hours_for_now() > 10  # Ten

    @staticmethod
    def can_create(classroom: Classroom, datetime, teacher: User, client: Client):
        if Lesson.objects.filter(classroom=classroom, datetime=datetime).count():
            return False

        if Lesson.objects.filter(teacher=teacher, datetime=datetime).count():
            return False

        if Lesson.objects.filter(client_subscription__client=client, datetime=datetime).count():
            return False

        return True

    def __str__(self):
        client = self.client_subscription.client
        dt = self.datetime.strftime('%d.%m.%Y %H:%M')
        return f"{client} / {self.teacher}, {self.classroom}, {dt}"


class LessonComment(Model):
    lesson = models.ForeignKey(Lesson, models.CASCADE)
    comment = models.TextField(max_length=500, blank=True)

    class Meta:
        verbose_name = _('Lesson comment')
        verbose_name_plural = _('Lesson comments')

    def __str__(self):
        dt = self.created_at.strftime('%d.%m.%Y %H:%M:%S')
        return f"{dt} {self.creator}: {self.comment}"


class Payment(Model):
    client_subscription = models.ForeignKey(ClientSubscription, models.CASCADE)
    payment_type = models.CharField(max_length=10, choices=PaymentType.choices)
    amount = models.FloatField(blank=True, default=000)
    comment = models.TextField(max_length=200, blank=True)

    class Meta:
        verbose_name = _('Payment')
        verbose_name_plural = _('Payments')

vocalkiev/apps/crm/apps/schedule/views.py
import calendar
from django.utils import timezone

from django.http import HttpResponse
from django.shortcuts import redirect
from django.utils.translation import ugettext as _
from django.template import loader

from vocalkiev.apps.crm.models import Place, Classroom, Lesson


def index(request):
    today = timezone.now()
    return redirect('crm-schedule-day', year=today.year, month=today.month, day=today.day)


def schedule_day(request, year=2021, month=0, day=0, place_id=0):
    places = Place.objects.all()
    calendar.setfirstweekday(calendar.MONDAY)
    try:
        monthdays = calendar.Calendar().monthdayscalendar(year, month)
    except calendar.IllegalMonthError:
        monthdays = []

    years = []
    for y in range(timezone.now().year, timezone.now().today().year + 3):
        years.append(y)

    months = []
    for m in calendar.month_name:
        if m:
            months.append(m)

    weekdays = []
    for wd in monthdays:
        for di, d in enumerate(wd):
            if d > 0:
                weekdays.append(list(calendar.day_name)[di])

    place = places.filter(id=place_id).first()
    classrooms = Classroom.objects.filter(place_id=place.id) if place else []

    data = []

    if year and month and day:
        lessons = Lesson.objects.filter(datetime__year=year, datetime__month=month, datetime__day=day)
        for t in range(9, 22):
            row = {'time': str(t) + ':00'}
            for lesson in lessons.filter(datetime__hour=t):
                value_teacher = lesson.teacher.get_full_name()
                value_client = lesson.client_subscription.client.__str__()

                subject = lesson.client_subscription.subscription.subject
                if subject.__str__() != 'Вокал':
                    value_teacher += ' | ' + subject.__str__()
                    value_client += ' | ' + subject.__str__()

                row['dcr_' + str(lesson.classroom.id) + '_t'] = value_teacher
                row['dcr_' + str(lesson.classroom.id) + '_c'] = value_client
            data.append(row)

    template = loader.get_template('schedule/day.html')
    context = {
        'places': places,
        'year': year,
        'month': month,
        'month_name': months[month - 1] if month else '',
        'day': day,
        'place': place_id,
        'place_name': place.name if place else '',
        'monthdays': monthdays,
        'months': months,
        'years': years,
        'weekdays': weekdays,
        'classrooms': classrooms,
        'data': data
    }

    return HttpResponse(template.render(context, request))


def schedule(request, year=2021, month=1):
    places = Place.objects.all()
    classrooms = Classroom.objects.all()

    calendar.setfirstweekday(calendar.MONDAY)
    monthdays = calendar.Calendar().monthdayscalendar(year, month)
    data = []
    month_lessons = Lesson.objects.filter(datetime__year=year, datetime__month=month)
    for d in range(0, len(monthdays)):
        week_lessons = {}
        time = {
            'time': _('Date')
        }
        for imd, md in enumerate(monthdays[d]):
            if md > 0:
                time['d_' + str(imd + 1)] = md
                week_lessons[md] = month_lessons.filter(datetime__day=md)

        data.append(time)

        for t in range(9, 22):
            row = {
                'time': str(t) + ':00'
            }
            for imd, md in enumerate(monthdays[d]):
                if md > 0:
                    for l in week_lessons[md].filter(datetime__hour=t):
                        cs = l.client_subscription
                        row[get_dp(imd, l) + '_t'] = l.teacher.get_full_name()
                        row[get_dp(imd, l) + '_c'] = cs.client.get_full_name()
            data.append(row)

    months = []
    for m in calendar.month_name:
        if m:
            months.append(m)

    years = []
    for y in range(timezone.now().today().year, timezone.now().today().year + 3):
        years.append(y)

    template = loader.get_template('schedule/index.html')
    context = {
        'year': year,
        'month': month,
        'month_name': months[month - 1],
        'weekDays': calendar.day_name,
        'months': months,
        'years': years,
        'places': places,
        'classrooms': classrooms,
        'data': data
    }

    return HttpResponse(template.render(context, request))


def get_dp(imd: int, lesson: Lesson):
    cr = lesson.classroom
    p = cr.place
    return 'dp_' + str(imd + 1) + '_' + str(p.id) + '_' + str(cr.id)

vocalkiev/apps/crm/apps/schedule/templates/schedule/day.html
{% extends "crm/base.html" %}

{% load i18n %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/bootstrap-table.min.css' %}">
<style>
    #table .w50, #table .w100, #table td {
        max-width: 50px;
        white-space: nowrap;
        text-overflow: clip;
        overflow: hidden;
    }

    #table .w150 {
        max-width: 150px;
    }

    #table td {
        padding-top: 0.1em;
        padding-bottom: 0.1em;
    }
</style>
{% endblock %}

{% block title %}
{% translate "Schedule" %}
{{ place_name }}
{% if day %}{{ day }}{% endif %}
{% translate month_name %}
{{ year }}
{% endblock %}


{% block h1 %}{% translate "Schedule" %}{% endblock %}

{% block content %}
<form id="form">
    {% if month %}
        <label>
            <select name="day">
                <option value="0">--{% translate "Day" %}--</option>
                {% for wd in weekdays %}
                    <!-- {% cycle 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 as di %} -->
                    <option value="{{ di }}" {% if di == day %} selected {% endif %}>{{ di }} {% translate wd %}</option>
                    {% if wd == "Sunday" %}
                        <option value="" disabled>---</option>
                    {% endif %}
                {% endfor %}
            </select>
        </label>
    {% endif %}
    <label>
        <select name="month">
            <option value="0">--{% translate "Month" %}--</option>
            {% for m in months %}
            <!-- {% cycle 1 2 3 4 5 6 7 8 9 10 11 12 as mi %} -->
            <option value="{{ mi }}" {% if mi == month %} selected {% endif %}>{% translate m %}</option>
            {% endfor %}
        </select>
    </label>
    <label>
        <select name="year">
            <option value="0">--{% translate "Year" %}--</option>
            {% for y in years %}
            <option value="{{ y }}" {% if y == year %} selected {% endif %}>{{ y }}</option>
            {% endfor %}
        </select>
    </label>
    {% if day %}
        <label>
            <select name="place">
                <option value="0">--{% translate "Place" %}--</option>
                {% for p in places %}
                    <option value="{{ p.id }}" {% if p.id == place %} selected {% endif %}>{{ p.name }}</option>
                {% endfor %}
            </select>
        </label>
    {% endif %}
</form>

<table id="table" class="table-sm">
    <thead>
    <tr>
        {% for cr in classrooms %}
            <th colspan="3" class="w150">{{ cr.name }}</th>
        {% endfor %}
    </tr>
    <tr>
        {% for cr in classrooms %}
            <th data-halign="center" class="w50" data-field="time">{% translate "Time" %}</th>
            <th data-field="dcr_{{ cr.id }}_t" class="w50" data-cell-style="cellStyleTeacher">{% translate "Teacher" %}</th>
            <th data-field="dcr_{{ cr.id }}_c" class="w50" data-cell-style="cellStyleClient">{% translate "Client" %}</th>
        {% endfor %}
    </tr>
    </thead>
</table>
{% endblock %}

{% block data %}{{ data|json_script:"data" }}{% endblock %}

{% block script %}
<script src="{% static 'js/bootstrap-table.min.js' %}"></script>
<script>
    const $table = $('#table')
    const $form = $('#form')
    const $selectMonth = $form.find('[name="month"]').first()
    const $selectYear = $form.find('[name="year"]').first()
    const $selectDay = $form.find('[name="day"]').first()
    const $selectPlace = $form.find('[name="place"]').first()
    const RENT_TEXT = '| Аренда'

    function cellStyleTeacher(value, row, index) {
        let r = {}

        if (value) {
            r = {classes: 'bg-warning'}

            if (value.indexOf(RENT_TEXT) !== -1) {
                r.classes = 'bg-primary'
            }
        }

        return r
    }

    function cellStyleClient(value, row, index) {
        return cellStyleTeacher(value, row, index)
    }

    $(function () {
        const data = JSON.parse(document.getElementById('data').textContent)

        if (data.length) {
            $table.bootstrapTable({
                data,
                undefinedText: '',
            })

            $table.find('td').popover({
                content: function() { return $(this).text() },
                placement: 'top'
            })
        } else {
            $table.remove()
        }

        $selectYear.change(function() {
            $form.submit()
        })

        $selectMonth.change(function() {
            $form.submit()
        })

        $selectDay.change(function() {
            $form.submit()
        })

        $selectPlace.change(function() {
            $form.submit()
        })

        $form.submit(function(e) {
            e.preventDefault()
            let url = '{% url 'crm-schedule' %}'
            const y = $selectYear.val()
            const m = $selectMonth.val()
            const d = $selectDay.val()
            const p = $selectPlace.val()

            if (y > 0) {
                url += y + '/'

                if (m > 0) {
                    url += m + '/'

                    if (d > 0) {
                        url += d + '/'

                        if (p > 0) {
                            url += p + '/'
                        }
                    }
                }
            }

            location.href = url
        })
    })
</script>
{% endblock %}

vocalkiev/apps/crm/apps/schedule/templates/schedule/index.html
{% extends "crm/base.html" %}

{% load i18n %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/bootstrap-table.min.css' %}">
{% endblock %}

{% block title %}{% translate month_name %} {{ year }} {% translate "Schedule" %}{% endblock %}

{% block h1 %}{% translate month_name %} {{ year }} {% translate "Schedule" %}{% endblock %}

{% block content %}
<form id="form">
    {% translate 'Month' %}:
    <label>
        <select name="month">
            {% for m in months %}
                <!-- {% cycle 1 2 3 4 5 6 7 8 9 10 11 12 as mi %} -->
                <option value="{{ mi }}" {% if mi == month %} selected {% endif %}>{% translate m %}</option>
            {% endfor %}
        </select>
    </label>
    {% translate 'Year' %}:
    <label>
        <select name="year">
            {% for y in years %}
                <option value="{{ y }}" {% if y == year %} selected {% endif %}>{{ y }}</option>
            {% endfor %}
        </select>
    </label>
    <input type="submit" value="{% translate 'Go' %}">
</form>

<table id="table" class="table-sm">
    <thead>
    <tr>
        <th data-halign="center" rowspan="3">{% translate "Time" %}</th>
        {% for d in weekDays %}
            <th data-halign="center" colspan="{{ classrooms.count|add:classrooms.count|add:1 }}">
                {% translate d %}
            </th>
        {% endfor %}
    </tr>
    <tr>
        {% for d in weekDays %}
            <!-- {% cycle 1 2 3 4 5 6 7 as di %} -->
            <th rowspan="2">&nbsp;</th>
            {% for p in places %}
                <th data-halign="center" colspan="{{ p.classroom_set.count|add:p.classroom_set.count }}">
                    {{ p.name }}
                </th>
            {% endfor %}
        {% endfor %}
    </tr>
    <tr>
        {% for d in weekDays %}
            <!-- {% cycle 1 2 3 4 5 6 7 as di %} -->
            {% for p in places %}
                {% for cr in p.classroom_set.all %}
                    <th colspan="2">
                        {{ cr.name }}
                    </th>
                {% endfor %}
            {% endfor %}
        {% endfor %}
    </tr>
    <tr>
        <th data-halign="center" data-field="time">&nbsp;</th>
        {% for d in weekDays %}
            <!-- {% cycle 1 2 3 4 5 6 7 as di %} -->
            <th data-field="d_{{ di }}" data-align="center">&nbsp;</th>
            {% for p in places %}
                {% for cr in p.classroom_set.all %}
                    <th data-field="dp_{{ di }}_{{ p.id }}_{{ cr.id }}_t">
                        {% translate "Teacher" %}
                    </th>
                    <th data-field="dp_{{ di }}_{{ p.id }}_{{ cr.id }}_c">
                        {% translate "Client" %}
                    </th>
                {% endfor %}
            {% endfor %}
        {% endfor %}
    </tr>
    </thead>
</table>
{% endblock %}

{% block data %}{{ data|json_script:"data" }}{% endblock %}

{% block script %}
<script src="{% static 'js/bootstrap-table.min.js' %}"></script>
<script>
    const classrooms_qty = {{ classrooms.count }}
    const $table = $('#table')
    const $form = $('#form')

    $(function () {
        const data = JSON.parse(document.getElementById('data').textContent)

        $table.bootstrapTable({
            data,
            undefinedText: '',
            height: $(document).height() - $('body').offset().top - $form.height(),
            {#stickyHeader: true,#}
            {#stickyHeaderOffsetLeft: parseInt($('body').css('padding-left'), 10),#}
            {#stickyHeaderOffsetRight: parseInt($('body').css('padding-right'), 10),#}
            {#fixedColumns: true,#}
            {#fixedNumber: 1,#}
            {#fixedRightNumber: 0#}
        })

        for (let r = 0; r <= 5; r++) {
            for (let d = 1; d <= 7; d++) {
                const i = r * 14

                $('tr[data-index]').eq(i).addClass('row-date')
                $table.bootstrapTable('mergeCells', {index: i, field: 'd_' + d, colspan: classrooms_qty * 2 + 1})
            }
        }

        $form.submit(function(e) {
            e.preventDefault()
            const m = $form.find('[name="month"]').first().val()
            const y = $form.find('[name="year"]').first().val()
            location.href = '/ru/crm/schedule/' + y + '/' + m + '/'
        })
    })
</script>
{% endblock %}