vocalkiev/apps/crm/apps/lessons/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='crm-lessons'),
    path('reports', views.reports, name='crm-reports'),
    path('clients/create', views.create_client, name='crm-create-client'),
    path('subscriptions', views.show_subscriptions, name='crm-subscriptions'),
    path(
        'subscriptions/create/',
        views.create_client_subscription,
        name='crm-create-subscription'
    ),
    path(
        'subscriptions/create-rent/',
        views.create_rent_subscription,
        name='crm-create-rent'
    ),
    path(
        'subscriptions/<int:client_subscription_id>/archive/',
        views.archive_client_subscription,
        name='crm-archive-subscription'
    ),
    path(
        'subscriptions/<int:client_subscription_id>/lessons/',
        views.show_lessons,
        name='crm-subscription-lessons'
    ),
    path(
        'subscriptions/<int:client_subscription_id>/lessons/create/',
        views.create_lesson,
        name='crm-create-lesson'
    ),
    path('<int:lesson_id>/pass/', views.pass_lesson, name='crm-pass-lesson'),
    path('<int:lesson_id>/update/', views.update_lesson, name='crm-update-lesson'),
]

vocalkiev/urls.py
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from vocalkiev.settings import LOGIN_URL
from vocalkiev.apps.owner.admin import owner_admin_site
from django.contrib.auth.decorators import login_required, user_passes_test
from decorator_include import decorator_include
from django.contrib.auth.views import LoginView

urlpatterns = [
    path(LOGIN_URL, LoginView.as_view(template_name='admin/login.html'))
]

urlpatterns += i18n_patterns(
    path('', include('vocalkiev.apps.vocalkiev_com.urls')),
    path(
        'owner/',
        decorator_include(
            user_passes_test(lambda u: u.is_superuser, login_url=f'/{LOGIN_URL}'),
            owner_admin_site.urls
        )
    ),
    path('crm/', decorator_include(login_required(login_url=f'/{LOGIN_URL}'), include('vocalkiev.apps.crm.urls'))),
)

vocalkiev/apps/crm/models.py
from django.utils import timezone

from django.db import models
from django.contrib.auth.models import User as AuthUser
from django.utils.translation import gettext_lazy as _


class User(AuthUser):
    class Meta:
        proxy = True
        verbose_name = _('User')
        verbose_name_plural = _('Users')

    def __str__(self):
        return ('%s %s' % (self.first_name, self.last_name)).strip()


class Status(models.TextChoices):
    ACTIVE = 'ACTIVE', _('ACTIVE')
    INACTIVE = 'INACTIVE', _('INACTIVE')


class PaymentType(models.TextChoices):
    CASH = 'CASH', _('CASH')
    CARD = 'CARD', _('CARD')


class Model(models.Model):
    status = models.CharField(max_length=10, choices=Status.choices, default=Status.ACTIVE)
    creator = models.ForeignKey(
        User,
        models.CASCADE,
        related_name="%(app_label)s_%(class)s_related"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = models.Manager()

    class Meta:
        abstract = True


class Client(Model):
    first_name = models.CharField(blank=True, max_length=64)
    last_name = models.CharField(blank=True, max_length=64, default='')
    email = models.EmailField(blank=True)
    phone = models.CharField(blank=True, max_length=20)
    comment = models.TextField(blank=True)

    class Meta:
        verbose_name = _('Client')
        verbose_name_plural = _('Clients')

    def __str__(self):
        return ('%s %s' % (self.first_name, self.last_name)).strip()


class ClientComment(Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    comment = models.TextField(max_length=200, blank=True, default='')

    class Meta:
        verbose_name = _('Client Comment')
        verbose_name_plural = _('Client Comments')

    def __str__(self):
        dt = self.created_at.strftime('%d.%m.%Y %H:%M')
        return f"{dt} {self.creator}: {self.comment}"


class Place(Model):
    name = models.CharField(max_length=64)

    class Meta:
        verbose_name = _('Place')
        verbose_name_plural = _('Places')

    def __str__(self):
        return self.name


class Classroom(Model):
    place = models.ForeignKey(Place, models.CASCADE)
    name = models.CharField(max_length=64)

    class Meta:
        verbose_name = _('Classroom')
        verbose_name_plural = _('Classrooms')

    def __str__(self):
        return f"{self.place} {self.name}"


class Subject(Model):
    name = models.CharField(max_length=64)

    class Meta:
        verbose_name = _('Subject')
        verbose_name_plural = _('Subjects')

    def __str__(self):
        return self.name


class Subscription(Model):
    subject = models.ForeignKey(Subject, models.CASCADE)
    name = models.CharField(max_length=64)
    price = models.FloatField(default=0)
    percentage = models.FloatField(default=0)
    lessons_qty = models.IntegerField(default=0)
    percentage_if_absent = models.FloatField(default=0)

    class Meta:
        verbose_name = _('Subscription')
        verbose_name_plural = _('Subscriptions')

    def __str__(self):
        return f"{self.subject} {self.name} ({self.price}{_('uah')})"


class ClientSubscription(Model):
    subscription = models.ForeignKey(Subscription, models.CASCADE)
    client = models.ForeignKey(Client, models.CASCADE)
    teacher = models.ForeignKey(User, models.CASCADE, related_name='subscription_teacher')
    comment = models.TextField(max_length=500, blank=True)
    payment_type = models.CharField(max_length=10, choices=PaymentType.choices)

    class Meta:
        verbose_name = _('Client Subscription')
        verbose_name_plural = _('Client Subscriptions')

    def can_create_lesson(self):
        return self.subscription.lessons_qty > self.lesson_set.count()

    def get_passed_lessons_count(self):
        return self.lesson_set.filter(is_passed=True).count()

    def can_archive(self):
        return self.subscription.lessons_qty == self.get_passed_lessons_count()

    def __str__(self):
        return f"{self.client}, {self.teacher.last_name}, {self.subscription}"


class Lesson(Model):
    client_subscription = models.ForeignKey(ClientSubscription, models.CASCADE)
    teacher = models.ForeignKey(User, models.CASCADE, related_name='lesson_teacher')
    classroom = models.ForeignKey(Classroom, models.CASCADE)
    datetime = models.DateTimeField(_('Time of the event'))
    is_passed = models.BooleanField(_('Is passed'), default=False)
    was_absent = models.BooleanField(_('Was absent'), default=False)

    class Meta:
        verbose_name = _('Lesson')
        verbose_name_plural = _('Lessons')

    def teacher_amount(self):
        if not self.is_passed:
            return 0

        s = self.client_subscription.subscription
        lesson_price = s.price / s.lessons_qty
        percentage = s.percentage if not self.was_absent else s.percentage_if_absent
        return lesson_price * percentage / 100

    def can_pass(self):
        return not self.is_passed and timezone.now() > self.datetime

    def diff_in_hours_for_now(self):
        return (self.datetime - timezone.now()).total_seconds() / 60 / 60

    def can_update_by_teacher(self):
        return self.diff_in_hours_for_now() > 18  # Eighteen

    def can_update_by_administrator(self):
        return self.diff_in_hours_for_now() > 10  # Ten

    @staticmethod
    def can_create(classroom: Classroom, datetime, teacher: User, client: Client):
        if Lesson.objects.filter(classroom=classroom, datetime=datetime).count():
            return False

        if Lesson.objects.filter(teacher=teacher, datetime=datetime).count():
            return False

        if Lesson.objects.filter(client_subscription__client=client, datetime=datetime).count():
            return False

        return True

    def __str__(self):
        client = self.client_subscription.client
        dt = self.datetime.strftime('%d.%m.%Y %H:%M')
        return f"{client} / {self.teacher}, {self.classroom}, {dt}"


class LessonComment(Model):
    lesson = models.ForeignKey(Lesson, models.CASCADE)
    comment = models.TextField(max_length=500, blank=True)

    class Meta:
        verbose_name = _('Lesson comment')
        verbose_name_plural = _('Lesson comments')

    def __str__(self):
        dt = self.created_at.strftime('%d.%m.%Y %H:%M:%S')
        return f"{dt} {self.creator}: {self.comment}"


class Payment(Model):
    client_subscription = models.ForeignKey(ClientSubscription, models.CASCADE)
    payment_type = models.CharField(max_length=10, choices=PaymentType.choices)
    amount = models.FloatField(blank=True, default=000)
    comment = models.TextField(max_length=200, blank=True)

    class Meta:
        verbose_name = _('Payment')
        verbose_name_plural = _('Payments')

vocalkiev/apps/crm/apps/teacher/apps/lessons/views.py
import datetime

from django.shortcuts import render, get_object_or_404, redirect

from vocalkiev.apps.crm.apps.teacher.apps.lessons.forms import PlaceDateForm, TimeForm, ClassroomForm, PassLessonForm, \
    LessonReportsForm
from vocalkiev.apps.crm.models import ClientSubscription, Lesson, Classroom, LessonComment, User


def index(request):
    return redirect('crm-teacher-subscriptions')


def show_subscriptions(request):
    client_subscriptions = ClientSubscription.objects.filter(teacher_id=request.user.id)
    return render(request, 'teacher/lessons/subscriptions.html', {'client_subscriptions': client_subscriptions})


def show_lessons(request, client_subscription_id):
    client_subscription = ClientSubscription.objects.get(pk=client_subscription_id)
    lessons = Lesson.objects.filter(client_subscription__id=client_subscription.id)
    return render(
        request,
        'teacher/lessons/lessons.html',
        {'client_subscription': client_subscription, 'lessons': lessons}
    )


def create_lesson(request, client_subscription_id):
    client_subscription = get_object_or_404(ClientSubscription, pk=client_subscription_id)

    if not client_subscription.can_create_lesson():
        return redirect('crm-teacher-subscription-lessons', client_subscription_id=client_subscription.id)

    place = None
    date = None
    date_hour = None
    time_form = None
    classroom_form = None

    if request.method == 'POST':
        place_date_form = PlaceDateForm(client_subscription, data=request.POST)
        if place_date_form.is_valid():
            teacher = place_date_form.cleaned_data['teacher']
            place = place_date_form.cleaned_data['place']
            date = place_date_form.cleaned_data['date']

            time_form = TimeForm(client_subscription, teacher, request.POST)
            if time_form.is_valid():
                date_hour = time_form.cleaned_data['date_hour']

                if date_hour:
                    classroom_form = ClassroomForm(client_subscription, teacher, request.POST)

                    if classroom_form.is_valid():
                        date_hour = classroom_form.cleaned_data['date_hour']
                        classroom_id = classroom_form.cleaned_data['classroom']

                        if classroom_id:
                            classroom = get_object_or_404(Classroom, pk=classroom_id)

                            dt = datetime.datetime(date.year, date.month, date.day, date_hour)

                            new_lesson = Lesson.objects.create(
                                creator=request.user,
                                client_subscription=client_subscription,
                                classroom=classroom,
                                teacher=teacher,
                                datetime=dt,
                            )

                            new_lesson.save()

                            return redirect('crm-schedule-day-place',
                                            year=date.year,
                                            month=date.month,
                                            day=date.day,
                                            place_id=classroom.place.id
                                            )
    else:
        place_date_form = PlaceDateForm(client_subscription)

    return render(
        request,
        'teacher/lessons/create-lesson.html',
        {
            'client_subscription': client_subscription,
            'place': place,
            'date': date,
            'date_hour': date_hour,
            'place_date_form': place_date_form,
            'time_form': time_form,
            'classroom_form': classroom_form,
        }
    )


def pass_lesson(request, lesson_id):
    lesson = get_object_or_404(Lesson, pk=lesson_id)

    if not lesson.can_pass():
        return redirect('crm-teacher-subscription-lessons', client_subscription_id=lesson.client_subscription.id)

    if request.method == 'POST':
        pass_lesson_form = PassLessonForm(request.POST)
        if pass_lesson_form.is_valid():
            was_absent = pass_lesson_form.cleaned_data['was_absent']

            lesson.is_passed = True
            lesson.was_absent = was_absent
            lesson.save()

            if pass_lesson_form.cleaned_data.get('comment'):
                new_comment = LessonComment.objects.create(
                    creator=request.user,
                    lesson=lesson,
                    comment=pass_lesson_form.cleaned_data['comment']
                )
                new_comment.save()

            return redirect('crm-teacher-subscription-lessons', client_subscription_id=lesson.client_subscription.id)
    else:
        pass_lesson_form = PassLessonForm()

    return render(
        request,
        'teacher/lessons/pass-lesson.html',
        {
            'lesson': lesson,
            'form': pass_lesson_form
        }
    )


def reports(request):
    lessons = None
    year = None
    month = None
    half_month = None
    total = 0

    if request.method == 'POST':
        lesson_reports_form = LessonReportsForm(request.POST)

        if lesson_reports_form.is_valid():
            year = int(lesson_reports_form.cleaned_data['year'])
            month = int(lesson_reports_form.cleaned_data['month'])
            half_month = int(lesson_reports_form.cleaned_data['half_month'])

            if half_month == 1:
                lessons = Lesson.objects.filter(
                    teacher_id=request.user.id,
                    is_passed=True,
                    datetime__year=year,
                    datetime__month=month,
                    datetime__day__lte=15
                )
            else:
                lessons = Lesson.objects.filter(
                    teacher_id=request.user.id,
                    is_passed=True,
                    datetime__year=year,
                    datetime__month=month,
                    datetime__day__gte=16
                )

            for lesson in lessons:
                total += lesson.teacher_amount()
    else:
        lesson_reports_form = LessonReportsForm()

    return render(
        request,
        'teacher/lessons/reports.html',
        {
            'lessons': lessons,
            'form': lesson_reports_form,
            'year': year,
            'month': month,
            'total': total,
        }
    )

vocalkiev/apps/crm/apps/lessons/templates/lessons/create-client.html
{% extends "crm/base.html" %}

{% load i18n %}

{% block title %}{% translate "Client" %}{% endblock %}

{% block h1 %}{% translate "Client" %}{% endblock %}

{% block content %}
<p class="text-center">
    <a href="{% url 'crm-create-subscription' %}">{% translate "Create for existing client" %}</a>
</p>
{% include "lessons/includes/form.html" with form=form show_label=True %}
{% endblock %}

vocalkiev/apps/crm/apps/lessons/templates/lessons/create-lesson.html
{% extends "crm/base.html" %}

{% load i18n %}

{% block title %}{% translate "Lesson" %}: {{ client_subscription }}{% endblock %}

{% block h1 %}{{ client_subscription }}{% endblock %}

{% block content %}
{% include "lessons/includes/form.html" with form=place_date_form %}

{% if time_form %}
<div class="row mt-3">
    <div class="col">
        <h2 class="h5">{{ place.name }} {{ date|date:"d.m" }}</h2>
    </div>
</div>
{% include "lessons/includes/form.html" with form=time_form %}
{% endif %}

{% if classroom_form %}
<div class="row mt-3">
    <div class="col">
        <h3 class="h5">{{ date_hour }}:00</h3>
    </div>
</div>
{% include "lessons/includes/form.html" with form=classroom_form %}
{% endif %}
{% endblock %}

vocalkiev/apps/crm/apps/lessons/templates/lessons/create-rent.html
{% extends "crm/base.html" %}

{% load i18n %}
{% load has_group %}

{% block title %}{% translate "Rent" %}{% endblock %}

{% block h1 %}{% translate "Rent" %}{% endblock %}

{% block content %}
{% if request.user|has_group:"Administrator" %}
<p class="text-center">
    <a href="{% url 'crm-create-client' %}">{% translate "Create a new client" %}</a>
</p>
{% endif %}

{% include "lessons/includes/form.html" with form=form show_label=True %}
{% endblock %}

vocalkiev/apps/crm/apps/lessons/templates/lessons/create-subscription.html
{% extends "crm/base.html" %}

{% load i18n %}
{% load has_group %}

{% block title %}{% translate "Subscription" %}{% endblock %}

{% block h1 %}{% translate "Subscription" %}{% endblock %}

{% block content %}
{% if request.user|has_group:"Administrator" %}
<p class="text-center">
    <a href="{% url 'crm-create-client' %}">{% translate "Create a new client" %}</a>
</p>
{% endif %}

{% include "lessons/includes/form.html" with form=form show_label=True %}
{% endblock %}

vocalkiev/apps/crm/apps/lessons/templates/lessons/lessons.html
{% extends "crm/base.html" %}

{% load i18n %}
{% load static %}

{% block title %}{% translate "Lessons" %} {{ client_subscription }}{% endblock %}

{% block h1 %}{% translate "Lessons" %} {{ client_subscription }}{% endblock %}

{% block content %}
<div id="client" class="accordion mb-3">
    <div class="card">
        <div id="clientHeader" class="text-center pt-2 pb-2">
            <a href="#" data-toggle="collapse" data-target="#clientBlock">{% translate "Client" %}: {{ client_subscription.client }}</a>
        </div>

        <div id="clientBlock" class="collapse" data-parent="#client">
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    {% for cc in client_subscription.client.clientcomment_set.all %}
                        <li class="list-group-item">{{ cc }}</li>
                    {% endfor %}
                </ul>
                {% include "lessons/includes/form.html" with form=client_comment_form show_label=True %}
            </div>
        </div>
    </div>
</div>

{% if client_subscription.can_create_lesson %}
<p class="text-center">
    <a href="{% url 'crm-create-lesson' client_subscription.id %}">{% translate "Create" %}</a>
</p>
{% endif %}

{% if lessons %}
<ul class="list-group list-group-flush">
    {% for l in lessons %}
    <li class="list-group-item">
        {{ l }}

        {% if l.can_pass %}
        <a href="{% url 'crm-pass-lesson' l.id %}">{% translate "Pass" %}</a>
        {% endif %}

        {% if l.can_update_by_teacher and l.teacher == request.user %}
        <a href="{% url 'crm-update-lesson' l.id %}">{% translate "Change" %}</a>
        {% endif %}

        {% if l.lessoncomment_set.count %}
        <ul>
            {% for lc in l.lessoncomment_set.all %}
            <li>{{ lc }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </li>
    {% endfor %}
</ul>
{% else %}
<h5 class="text-center">{% translate 'No lessons' %}</h5>
{% endif %}

{% if client_subscription.can_archive %}
<p class="text-center">
    <a href="{% url 'crm-archive-subscription' client_subscription.id %}">{% translate "Archive" %}</a>
</p>
{% endif %}
{% endblock %}

vocalkiev/apps/crm/apps/lessons/templates/lessons/pass-lesson.html
{% extends "crm/base.html" %}

{% load i18n %}

{% block title %}{% translate "Lesson" %}: {{ lesson }}{% endblock %}

{% block h1 %}{% translate "Lesson" %}: {{ lesson }}{% endblock %}

{% block content %}
<form action="{% url 'crm-pass-lesson' lesson.id %}" method="post">
    {% csrf_token %}

    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}

    {% for field in form.visible_fields %}
    {% include "lessons/includes/field.html" with field=field show_label=True %}
    {% endfor %}
    <input type="submit" value="{% translate 'Go' %}">
</form>
{% endblock %}

vocalkiev/apps/crm/apps/lessons/templates/lessons/reports.html
{% extends "crm/base.html" %}

{% load i18n %}
{% load static %}

{% block title %}{% translate "Lesson reports" %}{% endblock %}

{% block h1 %}{% translate "Lesson reports" %}{% endblock %}

{% block content %}
<form action="{% url 'crm-reports' %}" method="post">
    {% csrf_token %}

    {% for field in form.visible_fields %}
    {% include "lessons/includes/field.html" with field=field %}
    {% endfor %}
    <input type="submit" value="{% translate 'Go' %}">
</form>

{% if year and month %}
<h3 class="mt-5">{{ month }}.{{ year }}</h3>
<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">{% translate "Client" %}</th>
        <th scope="col">{% translate "Subscription" %}</th>
        <th scope="col">{% translate "Classroom" %}</th>
        <th scope="col">{% translate "Datetime" %}</th>
        <th scope="col">{% translate "Was absent" %}</th>
        <th scope="col">{% translate "Amount" %}</th>
    </tr>
    </thead>
    <tbody>
    {% if lessons %}
    {% for l in lessons %}
    <tr>
        <th scope="row">{{ l.id }}</th>
        <td>{{ l.client_subscription.client }}</td>
        <td>{{ l.client_subscription.subscription }}</td>
        <td>{{ l.classroom }}</td>
        <td>{{ l.datetime }}</td>
        <td>{% if l.was_absent %}+{% endif %}</td>
        <td>{{ l.teacher_amount }}</td>
    </tr>
    {% endfor %}
    {% else %}
    <tr colspan="7">{% translate "No lessons" %}</tr>
    {% endif %}
    <tr>
        <th scope="row" colspan="6">{% translate "Total" %}</th>
        <td>{{ total }}</td>
    </tr>
    </tbody>
</table>
{% endif %}
{% endblock %}

vocalkiev/apps/crm/apps/lessons/templates/lessons/subscriptions.html
{% extends "crm/base.html" %}

{% load i18n %}
{% load static %}
{% load has_group %}

{% block title %}{% translate "Client Subscriptions" %}{% endblock %}

{% block h1 %}{% translate "Client Subscriptions" %}{% endblock %}

{% block content %}
{% if request.user|has_group:"Administrator" %}
<p class="text-center">
    <a href="{% url 'crm-create-subscription' %}">{% translate "Create subscription" %}</a><br>
    <a href="{% url 'crm-create-rent' %}">{% translate "Rent" %}</a>
</p>
{% endif %}

{% if client_subscriptions %}
<ul class="list-group list-group-flush">
    {% for cs in client_subscriptions %}
    <li class="list-group-item">
        {{ cs.created_at }}: <a href="{% url 'crm-subscription-lessons' cs.id %}">{{ cs }}</a>
        <br>
        {% translate "Lessons" %} ({% translate "is passed" %} / {% translate "declared" %} / {% translate "in all" %}): {{ cs.get_passed_lessons_count }} / {{ cs.lesson_set.count }} / {{ cs.subscription.lessons_qty }}
    </li>
    {% endfor %}
</ul>
{% else %}
<h5 class="text-center">{% translate 'No subscriptions' %}</h5>
{% endif %}
{% endblock %}

vocalkiev/apps/crm/apps/lessons/templates/lessons/update-lesson.html
{% extends "lessons/create-lesson.html" %}

{% load i18n %}

{% block title %}{% translate "Lesson" %}: {{ lesson }}{% endblock %}

{% block h1 %}{{ lesson }}{% endblock %}